export interface StudyGroup {
  name: string
  link: string
  memberCount: number
  description: string
}

export const WHATSAPP_GROUPS: Record<string, StudyGroup> = {
  waec: {
    name: "WAEC Study Group 2026",
    link: "https://chat.whatsapp.com/waec2026",
    memberCount: 2847,
    description: "Get daily WAEC tips, past questions discussions, and study reminders.",
  },
  neco: {
    name: "NECO Study Group 2026",
    link: "https://chat.whatsapp.com/neco2026",
    memberCount: 1532,
    description: "NECO SSCE prep community with shared resources and peer support.",
  },
  jamb: {
    name: "JAMB UTME Study Group 2026",
    link: "https://chat.whatsapp.com/jamb2026",
    memberCount: 4210,
    description: "Largest JAMB UTME prep group with daily practice questions.",
  },
  igcse: {
    name: "IGCSE Study Group 2026",
    link: "https://chat.whatsapp.com/igcse2026",
    memberCount: 1893,
    description: "Cambridge IGCSE students sharing revision tips and resources.",
  },
  sat: {
    name: "SAT Prep Group 2026",
    link: "https://chat.whatsapp.com/sat2026",
    memberCount: 976,
    description: "SAT preparation with strategy guides and practice discussions.",
  },
  nabteb: {
    name: "NABTEB Study Group 2026",
    link: "https://chat.whatsapp.com/nabteb2026",
    memberCount: 654,
    description: "Technical and vocational exam prep community.",
  },
  bece: {
    name: "BECE Prep Group 2026",
    link: "https://chat.whatsapp.com/bece2026",
    memberCount: 1123,
    description: "Junior secondary exam prep with basic subjects focus.",
  },
  ielts: {
    name: "IELTS Prep Group 2026",
    link: "https://chat.whatsapp.com/ielts2026",
    memberCount: 2105,
    description: "IELTS band 7+ preparation with speaking and writing practice.",
  },
  "primary-math-foundations": {
    name: "Primary Math Study Group",
    link: "https://chat.whatsapp.com/primarymath2026",
    memberCount: 534,
    description: "Fun math activities and support for primary learners.",
  },
  "igcse-math-mastery": {
    name: "IGCSE Math Mastery Group",
    link: "https://chat.whatsapp.com/igcsemath2026",
    memberCount: 891,
    description: "IGCSE Mathematics (0580) problem-solving community.",
  },
  "wassce-complete-prep": {
    name: "WASSCE Prep Squad",
    link: "https://chat.whatsapp.com/wassce2026",
    memberCount: 1567,
    description: "Full WASSCE preparation across all core subjects.",
  },
  "jamb-utme-success": {
    name: "JAMB UTME Success Group",
    link: "https://chat.whatsapp.com/jambutme2026",
    memberCount: 2109,
    description: "JAMB-focused prep with subject experts online daily.",
  },
  "advanced-python-architecture": {
    name: "Python Architecture Guild",
    link: "https://chat.whatsapp.com/python2026",
    memberCount: 423,
    description: "Advanced Python discussions, code reviews, and projects.",
  },
  "venture-scaling-growth": {
    name: "Venture Scaling Group",
    link: "https://chat.whatsapp.com/venture2026",
    memberCount: 287,
    description: "Founders sharing growth strategies and scaling tactics.",
  },
  "bsc-computer-science": {
    name: "BSc Computer Science Cohort",
    link: "https://chat.whatsapp.com/bscs2026",
    memberCount: 867,
    description: "Official BSc Computer Science program group — assignments, projects, and peer support.",
  },
  "bsc-business-administration": {
    name: "BSc Business Admin Cohort",
    link: "https://chat.whatsapp.com/bbacohort",
    memberCount: 623,
    description: "BSc Business Administration study group with case discussions and networking.",
  },
  "msc-data-science": {
    name: "MSc Data Science Research Group",
    link: "https://chat.whatsapp.com/mscds2026",
    memberCount: 412,
    description: "MSc Data Science program group — research discussions, thesis support, and code reviews.",
  },
  mba: {
    name: "MBA Executive Network",
    link: "https://chat.whatsapp.com/mbanetwork",
    memberCount: 345,
    description: "Executive MBA cohort group — leadership discussions, case studies, and networking.",
  },
  "bsc-information-technology": {
    name: "BSc Information Technology Cohort",
    link: "https://chat.whatsapp.com/bit2026",
    memberCount: 512,
    description: "BSc IT program group — networking, databases, web dev, and IT infrastructure discussions.",
  },
  "bsc-software-engineering": {
    name: "BSc Software Engineering Cohort",
    link: "https://chat.whatsapp.com/bse2026",
    memberCount: 478,
    description: "BSc Software Engineering program group — design patterns, DevOps, and project collaboration.",
  },
  "bsc-cybersecurity": {
    name: "BSc Cybersecurity Cohort",
    link: "https://chat.whatsapp.com/bcyber2026",
    memberCount: 534,
    description: "BSc Cybersecurity program group — network security, forensics, and CTF challenges.",
  },
  "bsc-artificial-intelligence": {
    name: "BSc Artificial Intelligence Cohort",
    link: "https://chat.whatsapp.com/bai2026",
    memberCount: 612,
    description: "BSc AI program group — ML, deep learning, NLP, and robotics discussions.",
  },
  "bsc-data-science-ug": {
    name: "BSc Data Science Cohort",
    link: "https://chat.whatsapp.com/bds2026",
    memberCount: 445,
    description: "BSc Data Science program group — statistics, visualization, and data engineering.",
  },
  "msc-artificial-intelligence": {
    name: "MSc Artificial Intelligence Research Group",
    link: "https://chat.whatsapp.com/mscai2026",
    memberCount: 289,
    description: "MSc AI program group — advanced ML, research papers, and thesis support.",
  },
  "msc-cybersecurity": {
    name: "MSc Cybersecurity Research Group",
    link: "https://chat.whatsapp.com/msccyber2026",
    memberCount: 234,
    description: "MSc Cybersecurity program group — advanced threats, cryptography, and security research.",
  },
  "msc-software-engineering": {
    name: "MSc Software Engineering Research Group",
    link: "https://chat.whatsapp.com/mscse2026",
    memberCount: 198,
    description: "MSc Software Engineering program group — architecture, quality, and advanced methodologies.",
  },
  "bsc-electrical-engineering": {
    name: "BSc Electrical Engineering Cohort",
    link: "https://chat.whatsapp.com/bee2026",
    memberCount: 356,
    description: "BSc Electrical Engineering program group — circuits, power systems, and electronics.",
  },
  "bsc-mechanical-engineering": {
    name: "BSc Mechanical Engineering Cohort",
    link: "https://chat.whatsapp.com/bme2026",
    memberCount: 312,
    description: "BSc Mechanical Engineering program group — thermodynamics, mechanics, and design.",
  },
  "bsc-civil-engineering": {
    name: "BSc Civil Engineering Cohort",
    link: "https://chat.whatsapp.com/bce2026",
    memberCount: 278,
    description: "BSc Civil Engineering program group — structures, geotechnics, and infrastructure.",
  },
  "bsc-chemical-engineering": {
    name: "BSc Chemical Engineering Cohort",
    link: "https://chat.whatsapp.com/bche2026",
    memberCount: 245,
    description: "BSc Chemical Engineering program group — process design, thermodynamics, and reactions.",
  },
  "bsc-biomedical-engineering": {
    name: "BSc Biomedical Engineering Cohort",
    link: "https://chat.whatsapp.com/bbme2026",
    memberCount: 189,
    description: "BSc Biomedical Engineering program group — medical devices, bioinformatics, and biomechanics.",
  },
  "bsc-petroleum-engineering": {
    name: "BSc Petroleum Engineering Cohort",
    link: "https://chat.whatsapp.com/bpe2026",
    memberCount: 167,
    description: "BSc Petroleum Engineering program group — drilling, reservoir engineering, and production.",
  },
  "msc-electrical-engineering": {
    name: "MSc Electrical Engineering Research Group",
    link: "https://chat.whatsapp.com/mscee2026",
    memberCount: 156,
    description: "MSc Electrical Engineering program group — advanced power systems and electronics research.",
  },
  "msc-mechanical-engineering": {
    name: "MSc Mechanical Engineering Research Group",
    link: "https://chat.whatsapp.com/mscme2026",
    memberCount: 134,
    description: "MSc Mechanical Engineering program group — advanced mechanics and thermal systems.",
  },
  "msc-civil-engineering": {
    name: "MSc Civil Engineering Research Group",
    link: "https://chat.whatsapp.com/mscce2026",
    memberCount: 112,
    description: "MSc Civil Engineering program group — structural analysis and advanced construction.",
  },
  "bsc-physics": {
    name: "BSc Physics Cohort",
    link: "https://chat.whatsapp.com/bphys2026",
    memberCount: 234,
    description: "BSc Physics program group — mechanics, electromagnetism, and quantum theory.",
  },
  "bsc-chemistry": {
    name: "BSc Chemistry Cohort",
    link: "https://chat.whatsapp.com/bchem2026",
    memberCount: 198,
    description: "BSc Chemistry program group — organic, inorganic, physical, and analytical chemistry.",
  },
  "bsc-biology": {
    name: "BSc Biology Cohort",
    link: "https://chat.whatsapp.com/bbio2026",
    memberCount: 267,
    description: "BSc Biology program group — genetics, ecology, microbiology, and molecular biology.",
  },
  "bsc-mathematics": {
    name: "BSc Mathematics Cohort",
    link: "https://chat.whatsapp.com/bmath2026",
    memberCount: 189,
    description: "BSc Mathematics program group — analysis, algebra, and problem-solving community.",
  },
  "bsc-biotechnology": {
    name: "BSc Biotechnology Cohort",
    link: "https://chat.whatsapp.com/bbiot2026",
    memberCount: 156,
    description: "BSc Biotechnology program group — genetic engineering, bioinformatics, and lab techniques.",
  },
  "bsc-environmental-science": {
    name: "BSc Environmental Science Cohort",
    link: "https://chat.whatsapp.com/bes2026",
    memberCount: 178,
    description: "BSc Environmental Science program group — ecology, conservation, and sustainability.",
  },
  "msc-physics": {
    name: "MSc Physics Research Group",
    link: "https://chat.whatsapp.com/mscphys2026",
    memberCount: 98,
    description: "MSc Physics program group — advanced quantum mechanics and theoretical physics.",
  },
  "msc-chemistry": {
    name: "MSc Chemistry Research Group",
    link: "https://chat.whatsapp.com/mscchem2026",
    memberCount: 87,
    description: "MSc Chemistry program group — advanced synthetic and analytical chemistry.",
  },
  "msc-biology": {
    name: "MSc Biology Research Group",
    link: "https://chat.whatsapp.com/mscbio2026",
    memberCount: 92,
    description: "MSc Biology program group — molecular biology and advanced life sciences.",
  },
  "bsc-accounting": {
    name: "BSc Accounting Cohort",
    link: "https://chat.whatsapp.com/bacc2026",
    memberCount: 345,
    description: "BSc Accounting program group — financial reporting, audit, and taxation discussions.",
  },
  "bsc-economics": {
    name: "BSc Economics Cohort",
    link: "https://chat.whatsapp.com/becon2026",
    memberCount: 298,
    description: "BSc Economics program group — micro, macro, econometrics, and policy analysis.",
  },
  "bsc-finance": {
    name: "BSc Finance Cohort",
    link: "https://chat.whatsapp.com/bfin2026",
    memberCount: 267,
    description: "BSc Finance program group — corporate finance, investments, and financial markets.",
  },
  "bsc-marketing": {
    name: "BSc Marketing Cohort",
    link: "https://chat.whatsapp.com/bmkt2026",
    memberCount: 223,
    description: "BSc Marketing program group — brand management, digital marketing, and consumer behavior.",
  },
  "msc-accounting-finance": {
    name: "MSc Accounting & Finance Research Group",
    link: "https://chat.whatsapp.com/mscaf2026",
    memberCount: 145,
    description: "MSc Accounting & Finance program group — advanced financial analysis and research.",
  },
  "msc-economics": {
    name: "MSc Economics Research Group",
    link: "https://chat.whatsapp.com/mscecon2026",
    memberCount: 123,
    description: "MSc Economics program group — advanced econometrics and economic theory.",
  },
  "msc-marketing": {
    name: "MSc Marketing Research Group",
    link: "https://chat.whatsapp.com/mscmkt2026",
    memberCount: 98,
    description: "MSc Marketing program group — strategic marketing and consumer insights.",
  },
  "bsc-psychology": {
    name: "BSc Psychology Cohort",
    link: "https://chat.whatsapp.com/bpsych2026",
    memberCount: 312,
    description: "BSc Psychology program group — cognitive, developmental, and social psychology.",
  },
  "bsc-sociology": {
    name: "BSc Sociology Cohort",
    link: "https://chat.whatsapp.com/bsoc2026",
    memberCount: 198,
    description: "BSc Sociology program group — social theory, research methods, and cultural studies.",
  },
  "bsc-political-science": {
    name: "BSc Political Science Cohort",
    link: "https://chat.whatsapp.com/bposc2026",
    memberCount: 234,
    description: "BSc Political Science program group — governance, political theory, and public policy.",
  },
  "bsc-international-relations": {
    name: "BSc International Relations Cohort",
    link: "https://chat.whatsapp.com/bir2026",
    memberCount: 189,
    description: "BSc International Relations program group — diplomacy, global politics, and security studies.",
  },
  "bsc-mass-communication": {
    name: "BSc Mass Communication Cohort",
    link: "https://chat.whatsapp.com/bmc2026",
    memberCount: 278,
    description: "BSc Mass Communication program group — journalism, media studies, and PR.",
  },
  "msc-psychology": {
    name: "MSc Psychology Research Group",
    link: "https://chat.whatsapp.com/mscpsych2026",
    memberCount: 112,
    description: "MSc Psychology program group — clinical psychology and advanced research methods.",
  },
  "msc-international-relations": {
    name: "MSc International Relations Research Group",
    link: "https://chat.whatsapp.com/mscir2026",
    memberCount: 87,
    description: "MSc International Relations program group — global security and international law.",
  },
  "bsc-english-literary-studies": {
    name: "BSc English & Literary Studies Cohort",
    link: "https://chat.whatsapp.com/beng2026",
    memberCount: 212,
    description: "BSc English program group — literature, criticism, and creative writing.",
  },
  "bsc-history": {
    name: "BSc History Cohort",
    link: "https://chat.whatsapp.com/bhist2026",
    memberCount: 145,
    description: "BSc History program group — world history, African studies, and historiography.",
  },
  "bsc-philosophy": {
    name: "BSc Philosophy Cohort",
    link: "https://chat.whatsapp.com/bphil2026",
    memberCount: 98,
    description: "BSc Philosophy program group — ethics, logic, metaphysics, and epistemology.",
  },
  "bsc-linguistics": {
    name: "BSc Linguistics Cohort",
    link: "https://chat.whatsapp.com/bling2026",
    memberCount: 87,
    description: "BSc Linguistics program group — phonetics, syntax, semantics, and language acquisition.",
  },
  "msc-english": {
    name: "MSc English Research Group",
    link: "https://chat.whatsapp.com/msceng2026",
    memberCount: 67,
    description: "MSc English program group — literary theory and advanced research in English studies.",
  },
  "bsc-nursing": {
    name: "BSc Nursing Cohort",
    link: "https://chat.whatsapp.com/bnurs2026",
    memberCount: 356,
    description: "BSc Nursing program group — clinical practice, patient care, and medical ethics.",
  },
  "bsc-public-health": {
    name: "BSc Public Health Cohort",
    link: "https://chat.whatsapp.com/bph2026",
    memberCount: 289,
    description: "BSc Public Health program group — epidemiology, health policy, and community health.",
  },
  "bsc-pharmacy": {
    name: "BSc Pharmacy Cohort",
    link: "https://chat.whatsapp.com/bpharm2026",
    memberCount: 234,
    description: "BSc Pharmacy program group — pharmacology, therapeutics, and pharmaceutical care.",
  },
  "bsc-medical-laboratory-science": {
    name: "BSc Medical Laboratory Science Cohort",
    link: "https://chat.whatsapp.com/bmls2026",
    memberCount: 198,
    description: "BSc MLS program group — clinical pathology, histopathology, and lab diagnostics.",
  },
  "msc-public-health": {
    name: "MSc Public Health Research Group",
    link: "https://chat.whatsapp.com/mscph2026",
    memberCount: 156,
    description: "MSc Public Health program group — advanced epidemiology and global health.",
  },
  "msc-nursing": {
    name: "MSc Nursing Research Group",
    link: "https://chat.whatsapp.com/mscnurs2026",
    memberCount: 112,
    description: "MSc Nursing program group — advanced practice and nursing research.",
  },
  llb: {
    name: "LLB Law Cohort",
    link: "https://chat.whatsapp.com/llb2026",
    memberCount: 423,
    description: "LLB Law program group — legal reasoning, case law, and moot court preparation.",
  },
  llm: {
    name: "LLM Master of Laws Research Group",
    link: "https://chat.whatsapp.com/llm2026",
    memberCount: 145,
    description: "LLM program group — advanced legal research and specialized legal studies.",
  },
  "bsc-education": {
    name: "BSc Education Cohort",
    link: "https://chat.whatsapp.com/bed2026",
    memberCount: 234,
    description: "BSc Education program group — teaching methods, curriculum design, and pedagogy.",
  },
  "bsc-educational-technology": {
    name: "BSc Educational Technology Cohort",
    link: "https://chat.whatsapp.com/bedtech2026",
    memberCount: 156,
    description: "BSc EdTech program group — instructional design, e-learning, and digital tools.",
  },
  "msc-education": {
    name: "MSc Education Research Group",
    link: "https://chat.whatsapp.com/msced2026",
    memberCount: 98,
    description: "MSc Education program group — advanced pedagogy and educational leadership.",
  },
  "bsc-agriculture": {
    name: "BSc Agriculture Cohort",
    link: "https://chat.whatsapp.com/bagri2026",
    memberCount: 267,
    description: "BSc Agriculture program group — crop science, animal husbandry, and agribusiness.",
  },
  "bsc-agricultural-economics": {
    name: "BSc Agricultural Economics Cohort",
    link: "https://chat.whatsapp.com/bagecon2026",
    memberCount: 134,
    description: "BSc Agricultural Economics program group — farm management and agribusiness economics.",
  },
  "msc-agriculture": {
    name: "MSc Agriculture Research Group",
    link: "https://chat.whatsapp.com/mscagri2026",
    memberCount: 78,
    description: "MSc Agriculture program group — advanced crop science and sustainable agriculture.",
  },
  "msc-biotechnology": {
    name: "MSc Biotechnology Research Group",
    link: "https://chat.whatsapp.com/mscbiot2026",
    memberCount: 89,
    description: "MSc Biotechnology program group — genetic engineering and bio-innovation research.",
  },
  "msc-environmental-science": {
    name: "MSc Environmental Science Research Group",
    link: "https://chat.whatsapp.com/mscenviro2026",
    memberCount: 76,
    description: "MSc Environmental Science program group — climate change and sustainability research.",
  },
  "msc-finance": {
    name: "MSc Finance Research Group",
    link: "https://chat.whatsapp.com/mscfin2026",
    memberCount: 134,
    description: "MSc Finance program group — advanced financial theory and quantitative finance.",
  },
  "msc-data-science-analytics": {
    name: "MSc Data Science & Analytics Research Group",
    link: "https://chat.whatsapp.com/mscdsa2026",
    memberCount: 167,
    description: "MSc Data Science & Analytics program group — big data, ML, and business analytics.",
  },
  "msc-human-resource-management": {
    name: "MSc HRM Research Group",
    link: "https://chat.whatsapp.com/mschrm2026",
    memberCount: 112,
    description: "MSc Human Resource Management program group — talent management and organizational behavior.",
  },
  "msc-project-management": {
    name: "MSc Project Management Research Group",
    link: "https://chat.whatsapp.com/mscpm2026",
    memberCount: 145,
    description: "MSc Project Management program group — agile, risk management, and project leadership.",
  },
  "msc-supply-chain-management": {
    name: "MSc Supply Chain Management Research Group",
    link: "https://chat.whatsapp.com/mscscm2026",
    memberCount: 98,
    description: "MSc Supply Chain Management program group — logistics, operations, and supply chain strategy.",
  },
  "msc-architecture": {
    name: "MSc Architecture Research Group",
    link: "https://chat.whatsapp.com/mscarch2026",
    memberCount: 87,
    description: "MSc Architecture program group — design theory, urban planning, and sustainable architecture.",
  },
  "msc-petroleum-engineering": {
    name: "MSc Petroleum Engineering Research Group",
    link: "https://chat.whatsapp.com/mscpe2026",
    memberCount: 67,
    description: "MSc Petroleum Engineering program group — advanced drilling and reservoir engineering.",
  },
}

export function getWhatsAppGroup(slug: string): StudyGroup | undefined {
  return WHATSAPP_GROUPS[slug]
}

export function getAllExamGroups(): StudyGroup[] {
  const examSlugs = ["waec", "neco", "jamb", "igcse", "sat", "nabteb", "bece", "ielts"]
  return examSlugs.map((s) => WHATSAPP_GROUPS[s]).filter(Boolean)
}

export function getAllCourseGroups(): StudyGroup[] {
  const courseSlugs = [
    "primary-math-foundations",
    "igcse-math-mastery",
    "wassce-complete-prep",
    "jamb-utme-success",
    "advanced-python-architecture",
    "venture-scaling-growth",
    "bsc-computer-science",
    "bsc-business-administration",
    "msc-data-science",
    "mba",
    "bsc-information-technology",
    "bsc-software-engineering",
    "bsc-cybersecurity",
    "bsc-artificial-intelligence",
    "bsc-data-science-ug",
    "msc-artificial-intelligence",
    "msc-cybersecurity",
    "msc-software-engineering",
    "bsc-electrical-engineering",
    "bsc-mechanical-engineering",
    "bsc-civil-engineering",
    "bsc-chemical-engineering",
    "bsc-biomedical-engineering",
    "bsc-petroleum-engineering",
    "msc-electrical-engineering",
    "msc-mechanical-engineering",
    "msc-civil-engineering",
    "bsc-physics",
    "bsc-chemistry",
    "bsc-biology",
    "bsc-mathematics",
    "bsc-biotechnology",
    "bsc-environmental-science",
    "msc-physics",
    "msc-chemistry",
    "msc-biology",
    "bsc-accounting",
    "bsc-economics",
    "bsc-finance",
    "bsc-marketing",
    "msc-accounting-finance",
    "msc-economics",
    "msc-marketing",
    "bsc-psychology",
    "bsc-sociology",
    "bsc-political-science",
    "bsc-international-relations",
    "bsc-mass-communication",
    "msc-psychology",
    "msc-international-relations",
    "bsc-english-literary-studies",
    "bsc-history",
    "bsc-philosophy",
    "bsc-linguistics",
    "msc-english",
    "bsc-nursing",
    "bsc-public-health",
    "bsc-pharmacy",
    "bsc-medical-laboratory-science",
    "msc-public-health",
    "msc-nursing",
    "llb",
    "llm",
    "bsc-education",
    "bsc-educational-technology",
    "msc-education",
    "bsc-agriculture",
    "bsc-agricultural-economics",
    "msc-agriculture",
    "msc-biotechnology",
    "msc-environmental-science",
    "msc-finance",
    "msc-data-science-analytics",
    "msc-human-resource-management",
    "msc-project-management",
    "msc-supply-chain-management",
    "msc-architecture",
    "msc-petroleum-engineering",
  ]
  return courseSlugs.map((s) => WHATSAPP_GROUPS[s]).filter(Boolean)
}
